[package]
name = "wapr"
version = "0.1.0"
authors = ["Daniel Olano <daniel.olano@daimler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
